name: ci-comeandgo-workflow
on: [push]
jobs:
  check-application:
	runs-on: ubuntu-latest
	steps:
	- uses: actions/checkout@v3
	- name: Setup dotnet
	- uses: actions/setup-dotnet@v3
		with:
		dotnet-version: '7.0.x'
	- run: dotnet test
	- run: dotnet build  --project ./ComeAndGoCore/ComeAndGoCore.csproj